name: weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.1.1
  retrofit: '>=4.0.0 <5.0.0'
  intl: ^0.18.1
  flutter_dotenv: ^5.0.2
  floor: ^1.4.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.6
  google_maps_flutter: ^2.2.6
  shared_preferences: ^2.1.0
  change_app_package_name: ^1.1.0

dev_dependencies: 
  retrofit_generator: '>=6.0.0 <7.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.0
  floor_generator: ^1.4.1
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - config.env
    - assets/icons/

